[package]
name = "cockatiel"
version = "0.1.0"
edition = "2021"

[dependencies]
macros = { path = "../macros" }
bevy = { workspace = true }
if_chain = { workspace = true }

hashbrown = { workspace = true }
bevy_log = { workspace = true }